[project]
name = "watchcat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chuyang Chen", email = "chuyangchen2018@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "agno>=1.4.5",
    "click>=8.1.8",
    "sqlite-vec>=0.1.6",
    "tqdm>=4.67.1",
]
license = {file = "LICENSE"}

[project.scripts]
watchcat = "watchcat:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
